"""Generate the windsock drawables, one per standing band count.

Geometry (dp, must match WindSockGeometry in WindSock.kt): a 64 dp square with the sock's
mouth at the centre and the sock extending upward. Mouth half-width 5.3, tip half-width 1.3,
band length 6.4, five bands at most, orange first. The taper runs mouth to tip over the whole
length, so every sock is a complete sock; only the length and the band count change.
"""

from pathlib import Path

SIZE = 64.0
MOUTH = 5.3
TIP = 1.3
BAND = 6.4
MAX_BANDS = 5
STROKE = 2.0
ORANGE = "#FF6A00"
WHITE = "#FFFFFF"
OUT_DIR = Path(__file__).resolve().parent.parent / "app/src/main/res/drawable"


def fmt(v: float) -> str:
    return f"{v:.2f}".rstrip("0").rstrip(".")


def polygon(points: list[tuple[float, float]]) -> str:
    head, *rest = points
    return (
        f"M{fmt(head[0])},{fmt(head[1])} "
        + " ".join(f"L{fmt(x)},{fmt(y)}" for x, y in rest)
        + " Z"
    )


def sock(bands: int) -> str:
    cx = cy = SIZE / 2
    length = BAND * bands

    def half_width(up: float) -> float:
        return MOUTH - (MOUTH - TIP) * up / length

    paths = []
    for b in range(bands):
        y0, y1 = b * BAND, (b + 1) * BAND
        fill = ORANGE if b % 2 == 0 else WHITE
        pts = [
            (cx - half_width(y0), cy - y0),
            (cx + half_width(y0), cy - y0),
            (cx + half_width(y1), cy - y1),
            (cx - half_width(y1), cy - y1),
        ]
        paths.append(
            f'    <path\n        android:fillColor="{fill}"\n'
            f'        android:pathData="{polygon(pts)}"/>'
        )
    outline = [
        (cx - MOUTH, cy),
        (cx + MOUTH, cy),
        (cx + TIP, cy - length),
        (cx - TIP, cy - length),
    ]
    paths.append(
        "    <!-- outline -->\n    <path\n"
        f'        android:pathData="{polygon(outline)}"\n'
        '        android:strokeColor="#000000"\n'
        f'        android:strokeWidth="{fmt(STROKE)}"\n'
        '        android:strokeLineJoin="round"/>'
    )
    body = "\n".join(paths)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/gen_wind_sock_drawables.py; do not edit by hand.\n"
        f"     Windsock from above with {bands} standing band(s), mouth at the centre. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{fmt(SIZE)}dp"\n'
        f'    android:height="{fmt(SIZE)}dp"\n'
        f'    android:viewportWidth="{fmt(SIZE)}"\n'
        f'    android:viewportHeight="{fmt(SIZE)}">\n'
        f"{body}\n"
        "</vector>\n"
    )


def main() -> None:
    for bands in range(1, MAX_BANDS + 1):
        path = OUT_DIR / f"ic_wind_sock_{bands}.xml"
        path.write_text(sock(bands))
        print(path)


if __name__ == "__main__":
    main()
