"""Generate per-grade-colour chevron drawables for the climber map overlay.

Parses `FieldColors.kt` for every unique `Color(0xFFxxxxxx)` reference inside
a `_GRADE_BANDS*` list, then writes:

1. One Android vector drawable per colour at
   `app/src/main/res/drawable/ic_climber_chevron_<rrggbb>.xml`.
2. A Kotlin lookup at
   `app/src/main/kotlin/.../datatype/shared/ChevronDrawables.kt`
   mapping the ARGB `Int` value to the matching `@DrawableRes Int`.

Stale variants that no longer correspond to a current palette colour are
removed.

The pentagon path matches the rideapp's native `directional_arrow.xml`
(viewport 49 x 41); only the dp size differs so our overlay chevrons just
cover the native ones.

The fallback drawable `ic_climber_chevron.xml` (neutral grey) is hand-
maintained and is left untouched.

Usage
-----
uv run scripts/generate_chevron_drawables.py
"""

from __future__ import annotations

import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ROOT = Path(__file__).parent.parent
_SHARED_KT = (
    _ROOT / "app/src/main/kotlin/com/jpweytjens/barberfish/datatype/shared"
)
FIELD_COLORS_KT = _SHARED_KT / "FieldColors.kt"
CHEVRON_DRAWABLES_KT = _SHARED_KT / "ChevronDrawables.kt"
DRAWABLE_DIR = _ROOT / "app/src/main/res/drawable"
FALLBACK_NAME = "ic_climber_chevron.xml"  # hand-maintained, never overwritten

# ---------------------------------------------------------------------------
# Drawable template
# ---------------------------------------------------------------------------

# Pentagon path copied verbatim from the rideapp's `directional_arrow.xml`
# so our chevron silhouette matches what Karoo draws on the route.
_PATH_DATA = (
    "M4.98657 27.8609L4.37199 34.404L9.74576 30.615L24.2457 20.3912"
    "L39.2945 30.6442L44.8779 34.4483L44.0064 27.7454L42.7082 17.7616"
    "L42.5292 16.3848L41.369 15.6232L25.8962 5.46694L24.2252 4.37008"
    "L22.558 5.4774L7.2667 15.6337L6.05976 16.4353L5.92434 17.8771"
    "L4.98657 27.8609Z"
)

_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_chevron_drawables.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="14dp"
    android:height="17dp"
    android:viewportWidth="49"
    android:viewportHeight="41">
    <path
        android:fillColor="#{rrggbb}"
        android:pathData="{path}"
        android:strokeColor="#000000"
        android:strokeWidth="6.0584"/>
</vector>
"""


# ---------------------------------------------------------------------------
# Palette extraction
# ---------------------------------------------------------------------------

# Match `..._GRADE_BANDS(_READABLE)? = listOf(\n ... \n)` — bounded by a `)` on its
# own line so the non-greedy body doesn't terminate at the first `Color(0x...)`'s
# closing paren.
_BAND_BLOCK = re.compile(
    r"_GRADE_BANDS(?:_READABLE)?\s*=\s*listOf\(\n(.*?)\n\)",
    re.DOTALL,
)
_COLOR_REF = re.compile(r"Color\(0x([Ff]{2})([0-9A-Fa-f]{6})\)")


def extract_palette_colors(source: str) -> list[str]:
    """Return the unique 6-character RGB hex codes used in grade-band palettes.

    Parameters
    ----------
    source : str
        Contents of `FieldColors.kt`.

    Returns
    -------
    list[str]
        Lowercase six-character hex strings, sorted for stable output.
    """
    colors: set[str] = set()
    for block in _BAND_BLOCK.finditer(source):
        for _, rgb in _COLOR_REF.findall(block.group(1)):
            colors.add(rgb.lower())
    return sorted(colors)


# ---------------------------------------------------------------------------
# Filesystem sync
# ---------------------------------------------------------------------------


def sync_drawables(colors: list[str]) -> tuple[int, int]:
    """Write one drawable per colour; remove stale ones.

    Parameters
    ----------
    colors : list[str]
        Lowercase six-character RGB hex strings.

    Returns
    -------
    tuple[int, int]
        Count of (written, removed) drawables.
    """
    target_names = {f"ic_climber_chevron_{c}.xml" for c in colors}
    existing = {
        p.name
        for p in DRAWABLE_DIR.glob("ic_climber_chevron_*.xml")
    }

    written = 0
    for rrggbb in colors:
        path = DRAWABLE_DIR / f"ic_climber_chevron_{rrggbb}.xml"
        path.write_text(_TEMPLATE.format(rrggbb=rrggbb, path=_PATH_DATA))
        written += 1

    stale = existing - target_names - {FALLBACK_NAME}
    for name in stale:
        (DRAWABLE_DIR / name).unlink()

    return written, len(stale)


_LOOKUP_TEMPLATE = """package com.jpweytjens.barberfish.datatype.shared

import androidx.annotation.DrawableRes
import com.jpweytjens.barberfish.R

// Generated by scripts/generate_chevron_drawables.py. Do not edit by hand.
// Maps grade-band ARGB ints to the matching pre-baked chevron drawable.

@DrawableRes
internal fun gradeChevronDrawable(colorArgb: Int): Int = when (colorArgb) {{
{cases}
    else -> R.drawable.ic_climber_chevron
}}
"""


def write_lookup(colors: list[str]) -> None:
    """Write the `gradeChevronDrawable` switch to `ChevronDrawables.kt`.

    Parameters
    ----------
    colors : list[str]
        Lowercase six-character RGB hex strings.
    """
    cases = "\n".join(
        f"    0xFF{c}.toInt() -> R.drawable.ic_climber_chevron_{c}"
        for c in colors
    )
    CHEVRON_DRAWABLES_KT.write_text(_LOOKUP_TEMPLATE.format(cases=cases))


def main() -> None:
    source = FIELD_COLORS_KT.read_text()
    colors = extract_palette_colors(source)
    written, removed = sync_drawables(colors)
    write_lookup(colors)
    print(f"{written} chevron drawables written, {removed} stale removed.")
    print(f"Lookup written to {CHEVRON_DRAWABLES_KT.relative_to(_ROOT)}.")
    print("Colours:")
    for c in colors:
        print(f"  #{c}")


if __name__ == "__main__":
    main()
