"""Generate per-grade-colour chevron drawables for the climber map overlay.

Parses `GradeBands.kt` for every unique colour reference inside a
`_GRADE_BANDS*` list, then writes:

1. One Android vector drawable per colour at
   `app/src/main/res/drawable/ic_climber_chevron_<rrggbb>.xml`.
2. A Kotlin lookup at
   `app/src/main/kotlin/.../datatype/shared/ChevronDrawables.kt`
   mapping the ARGB `Int` value to the matching `@DrawableRes Int`.

Stale variants that no longer correspond to a current palette colour are
removed.

Every drawable shares one silhouette and differs only in fill colour, so the
overlay reads along the route as a grade ramp rather than as a change of shape.

The fallback drawable `ic_climber_chevron.xml` (neutral grey) is hand-
maintained and is left untouched.

Usage
-----
uv run scripts/generate_chevron_drawables.py
"""

from __future__ import annotations

import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ROOT = Path(__file__).parent.parent
_SHARED_KT = (
    _ROOT / "app/src/main/kotlin/com/jpweytjens/barberfish/datatype/shared"
)
FIELD_COLORS_KT = _SHARED_KT / "FieldColors.kt"
GRADE_BANDS_KT = _SHARED_KT / "GradeBands.kt"
ZONE_COLORING_KT = _SHARED_KT / "ZoneColoring.kt"
CHEVRON_DRAWABLES_KT = _SHARED_KT / "ChevronDrawables.kt"
DRAWABLE_DIR = _ROOT / "app/src/main/res/drawable"
FALLBACK_NAME = "ic_climber_chevron.xml"  # hand-maintained, never overwritten

# ---------------------------------------------------------------------------
# Drawable template
# ---------------------------------------------------------------------------

# Chevron silhouette: a wide, shallow arrowhead in a 25 x 17 viewport, drawn 1:1
# at 25 x 17 dp. Shape and size are tuned so an overlay chevron reads as one of
# the route's own direction markers at typical map zooms, not as a second symbol
# layered on top.
_PATH_DATA = (
    "M1,12.294C1,10.385 1.685,8.6 2.848,7.41L3.087,7.181L3.138,7.134"
    "L3.195,7.095L11.675,1.326C12.15,1.003 12.775,1.003 13.25,1.326"
    "L21.729,7.095L21.787,7.134L21.838,7.181C23.145,8.363 23.925,10.258"
    " 23.925,12.294V12.304L23.91,13.815C23.9,14.894 22.725,15.556"
    " 21.797,15.007L12.462,9.479L3.128,15.007C2.2,15.556 1.025,14.894"
    " 1.015,13.815L1,12.304V12.294Z"
)

_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_chevron_drawables.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="25dp"
    android:height="17dp"
    android:viewportWidth="25"
    android:viewportHeight="17">
    <path
        android:fillColor="#{rrggbb}"
        android:pathData="{path}"
        android:strokeColor="#000000"
        android:strokeWidth="2"/>
</vector>
"""


# ---------------------------------------------------------------------------
# Palette extraction
# ---------------------------------------------------------------------------

# Match `..._GRADE_BANDS<suffix> = listOf(\n ... \n)` — bounded by a `)` on its
# own line so the non-greedy body doesn't terminate at the first `Color(0x...)`'s
# closing paren. The suffix covers the readable dark/light variants.
_BAND_BLOCK = re.compile(
    r"_GRADE_BANDS\w*\s*=\s*listOf\(\n(.*?)\n\s*\)\n",
    re.DOTALL,
)
# `val name = [\n] listOf(\n ... \n)` — a named colour array (e.g. karooPowerColors).
_ARRAY_BLOCK = re.compile(
    r"val\s+(\w+)\s*=\s*(?:\n\s*)?listOf\(\n(.*?)\n\s*\)",
    re.DOTALL,
)
_COLOR_REF = re.compile(r"Color\(0x[Ff]{2}([0-9A-Fa-f]{6})\)")
# An indexed reference into a named colour array, e.g. `karooPowerColors[6]`.
_INDEX_REF = re.compile(r"(\w+)\[(\d+)\]")
# A band pointing at a named colour constant, e.g. `-2.0 to FlatGrey,`. The trailing
# `,`/`//`/end-of-line requirement is what keeps `to Color(0x...)` and
# `to karooPowerColors[6]` out.
_NAMED_REF = re.compile(r"to\s+([A-Za-z_]\w*)\s*(?:,|//|$)", re.MULTILINE)
# A named colour constant's definition, e.g. `internal val FlatGrey = Color(0xFFC4C4C4)`.
_NAMED_COLOR = re.compile(r"val\s+(\w+)\s*=\s*Color\(0x[Ff]{2}([0-9A-Fa-f]{6})\)")
# `LemonYellow` is the route-yellow filler the climber overlay paints on below-threshold
# segments inside a climb — chevrons there need a matching drawable too.
_FILLER_REF = re.compile(r"val\s+LemonYellow\s*=\s*Color\(0x[Ff]{2}([0-9A-Fa-f]{6})\)")


def extract_filler_color(field_colors: str) -> str:
    """Return the RGB hex of `LemonYellow`, the overlay's filler colour.

    Parameters
    ----------
    field_colors : str
        Contents of `FieldColors.kt`.

    Returns
    -------
    str
        Lowercase six-character hex string.
    """
    match = _FILLER_REF.search(field_colors)
    if match is None:
        raise SystemExit("LemonYellow not found in FieldColors.kt")
    return match.group(1).lower()


def parse_color_arrays(source: str) -> dict[str, list[str]]:
    """Return ordered RGB hex codes for each named `Color(0x...)` array.

    Grade-band palettes index into shared palettes (`karooPowerColors[6]`,
    `hsluvPowerColors[0]`, ...) defined in `ZoneColoring.kt`. This resolves
    those array names to their colour lists.

    Parameters
    ----------
    source : str
        Contents of `ZoneColoring.kt`.

    Returns
    -------
    dict[str, list[str]]
        Array name -> ordered lowercase six-character hex strings.
    """
    arrays: dict[str, list[str]] = {}
    for name, body in _ARRAY_BLOCK.findall(source):
        hexes = [m.lower() for m in _COLOR_REF.findall(body)]
        if hexes:
            arrays[name] = hexes
    return arrays


def parse_named_colors(source: str) -> dict[str, str]:
    """Return the RGB hex of each `val Name = Color(0x...)` constant.

    Grade bands may point at a shared named colour (`-2.0 to FlatGrey`) instead
    of spelling the literal out.

    Parameters
    ----------
    source : str
        Contents of `FieldColors.kt`.

    Returns
    -------
    dict[str, str]
        Constant name -> lowercase six-character hex string.
    """
    return {name: rgb.lower() for name, rgb in _NAMED_COLOR.findall(source)}


def extract_palette_colors(
    grade_bands: str,
    arrays: dict[str, list[str]],
    named: dict[str, str],
) -> list[str]:
    """Return the unique RGB hex codes used in every grade-band palette.

    Resolves inline `Color(0x...)` literals, indexed references into the shared
    colour [arrays], and [named] colour constants.

    Parameters
    ----------
    grade_bands : str
        Contents of `GradeBands.kt`.
    arrays : dict[str, list[str]]
        Named colour arrays from `parse_color_arrays`.
    named : dict[str, str]
        Named colour constants from `parse_named_colors`.

    Returns
    -------
    list[str]
        Lowercase six-character hex strings, sorted for stable output.
    """
    colors: set[str] = set()
    for block in _BAND_BLOCK.finditer(grade_bands):
        body = block.group(1)
        for rgb in _COLOR_REF.findall(body):
            colors.add(rgb.lower())
        for name, index in _INDEX_REF.findall(body):
            palette = arrays.get(name)
            if palette is None:
                raise SystemExit(
                    f"Unknown colour array '{name}' referenced in a grade band. "
                    f"Add it to ZoneColoring.kt or update this script."
                )
            colors.add(palette[int(index)])
        for name in _NAMED_REF.findall(body):
            rgb = named.get(name)
            if rgb is None:
                raise SystemExit(
                    f"Unknown colour constant '{name}' referenced in a grade band. "
                    f"Add it to FieldColors.kt or update this script."
                )
            colors.add(rgb)
    return sorted(colors)


# ---------------------------------------------------------------------------
# Filesystem sync
# ---------------------------------------------------------------------------


def sync_drawables(colors: list[str]) -> tuple[int, int]:
    """Write one drawable per colour; remove stale ones.

    Parameters
    ----------
    colors : list[str]
        Lowercase six-character RGB hex strings.

    Returns
    -------
    tuple[int, int]
        Count of (written, removed) drawables.
    """
    target_names = {f"ic_climber_chevron_{c}.xml" for c in colors}
    existing = {
        p.name
        for p in DRAWABLE_DIR.glob("ic_climber_chevron_*.xml")
    }

    written = 0
    for rrggbb in colors:
        path = DRAWABLE_DIR / f"ic_climber_chevron_{rrggbb}.xml"
        path.write_text(_TEMPLATE.format(rrggbb=rrggbb, path=_PATH_DATA))
        written += 1

    stale = existing - target_names - {FALLBACK_NAME}
    for name in stale:
        (DRAWABLE_DIR / name).unlink()

    return written, len(stale)


_LOOKUP_TEMPLATE = """package com.jpweytjens.barberfish.datatype.shared

import androidx.annotation.DrawableRes
import com.jpweytjens.barberfish.R

// Generated by scripts/generate_chevron_drawables.py. Do not edit by hand.
// Maps grade-band ARGB ints to the matching pre-baked chevron drawable.

@DrawableRes
internal fun gradeChevronDrawable(colorArgb: Int): Int =
    when (colorArgb) {{
{cases}
        else -> R.drawable.ic_climber_chevron
    }}
"""


def write_lookup(colors: list[str]) -> None:
    """Write the `gradeChevronDrawable` switch to `ChevronDrawables.kt`.

    Parameters
    ----------
    colors : list[str]
        Lowercase six-character RGB hex strings.
    """
    cases = "\n".join(
        f"        0xFF{c}.toInt() -> R.drawable.ic_climber_chevron_{c}"
        for c in colors
    )
    CHEVRON_DRAWABLES_KT.write_text(_LOOKUP_TEMPLATE.format(cases=cases))


def main() -> None:
    field_colors = FIELD_COLORS_KT.read_text()
    grade_bands = GRADE_BANDS_KT.read_text()
    arrays = parse_color_arrays(ZONE_COLORING_KT.read_text())
    named = parse_named_colors(field_colors)
    colors = sorted(
        set(extract_palette_colors(grade_bands, arrays, named))
        | {extract_filler_color(field_colors)}
    )
    written, removed = sync_drawables(colors)
    write_lookup(colors)
    print(f"{written} chevron drawables written, {removed} stale removed.")
    print(f"Lookup written to {CHEVRON_DRAWABLES_KT.relative_to(_ROOT)}.")
    print("Colours:")
    for c in colors:
        print(f"  #{c}")


if __name__ == "__main__":
    main()
