#!/usr/bin/env python3
"""Generate a fully synthetic ClimbPreviewFixture.kt for the config preview.

The preview is illustrative, not a real climb: a winding road that fills the square
and a grade profile that walks the whole green->red palette so the overlay shows off
its colours and chevrons. No GPX, no map capture, no registration. Tune the WAYPOINTS
(road shape) and GRADE_PROFILE (colours) below, then rerun.

Usage:
    python scripts/synth_climb_fixture.py \
        > app/src/main/kotlin/com/jpweytjens/barberfish/datatype/shared/ClimbPreviewFixture.kt
"""

import math

from gpx_to_climb_fixture import encode_polyline, square_bounds

# Road shape as (east_m, north_m) waypoints, climbing bottom -> top. Catmull-Rom rounds
# them into the road. Modelled on the Stelvio's stacked hairpins: a traverse in from the
# bottom-right, then tight switchbacks alternating left/right up a narrow corridor.
WAYPOINTS = [
    (1180, 70),  # bottom-right approach
    (840, 190),
    (560, 300),  # enter the hairpins
    (790, 365),  # hairpin R
    (560, 430),
    (370, 495),  # hairpin L
    (560, 560),
    (790, 625),  # hairpin R
    (560, 690),
    (370, 755),  # hairpin L
    (560, 820),
    (790, 885),  # hairpin R
    (560, 950),
    (370, 1015),  # hairpin L
    (560, 1080),
    (790, 1145),  # hairpin R
    (560, 1210),
    (620, 1340),  # exit toward the pass
    (560, 1470),
]

# Grade as (distance_fraction, grade_pct) control points, linearly interpolated. Kept
# deliberately heterogeneous (2% dark green -> 18% red and back) so the overlay shows off
# every palette band; the Stelvio reference only informs the road shape, not the grade.
GRADE_PROFILE = [
    (0.00, 2.0),
    (0.10, 3.0),
    (0.25, 6.5),
    (0.40, 10.0),
    (0.52, 18.0),
    (0.62, 13.0),
    (0.74, 8.0),
    (0.88, 5.0),
    (1.00, 3.0),
]

# Anchor the synthetic metres onto real lat/lng (alpine-ish) so web-mercator
# projection and the squared bounds behave exactly like a captured climb.
LAT0 = 45.20
LNG0 = 6.50
SAMPLES_PER_SEGMENT = 22


def catmull_rom(p0, p1, p2, p3, t):
    t2, t3 = t * t, t * t * t
    return (
        0.5
        * (
            (2 * p1[0])
            + (-p0[0] + p2[0]) * t
            + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
            + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
        ),
        0.5
        * (
            (2 * p1[1])
            + (-p0[1] + p2[1]) * t
            + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
            + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
        ),
    )


def smooth_path(pts):
    padded = [pts[0]] + pts + [pts[-1]]
    out = []
    for i in range(1, len(padded) - 2):
        for s in range(SAMPLES_PER_SEGMENT):
            out.append(
                catmull_rom(
                    padded[i - 1],
                    padded[i],
                    padded[i + 1],
                    padded[i + 2],
                    s / SAMPLES_PER_SEGMENT,
                )
            )
    out.append(pts[-1])
    return out


def grade_at(frac):
    for (f0, g0), (f1, g1) in zip(GRADE_PROFILE, GRADE_PROFILE[1:]):
        if f0 <= frac <= f1:
            w = 0.0 if f1 == f0 else (frac - f0) / (f1 - f0)
            return g0 + (g1 - g0) * w
    return GRADE_PROFILE[-1][1]


def main():
    path = smooth_path(WAYPOINTS)
    coslat = math.cos(math.radians(LAT0))
    latlng = [
        (LAT0 + north / 111320.0, LNG0 + east / (111320.0 * coslat))
        for (east, north) in path
    ]

    # Cumulative ground distance for the elevation channel.
    dists = [0.0]
    for (e0, n0), (e1, n1) in zip(path, path[1:]):
        dists.append(dists[-1] + math.hypot(e1 - e0, n1 - n0))
    total = dists[-1]

    elev = [0.0]
    for prev, cur in zip(dists, dists[1:]):
        g = grade_at(((prev + cur) / 2) / total)
        elev.append(elev[-1] + (cur - prev) * g / 100.0)

    route_poly = encode_polyline(latlng, 1e5)
    elev_poly = encode_polyline(list(zip(dists, elev)), 10.0)

    lats = [p[0] for p in latlng]
    lngs = [p[1] for p in latlng]
    min_lat, max_lat, min_lng, max_lng = square_bounds(
        min(lats), max(lats), min(lngs), max(lngs), margin=0.06
    )

    print("// Generated by scripts/synth_climb_fixture.py - do not edit by hand.")
    print("package com.jpweytjens.barberfish.datatype.shared")
    print()
    print("/** Synthetic route fixture for the climb overlay config preview: a winding")
    print(" *  climb whose grade walks the full palette. Not a real place. */")
    print("internal object ClimbPreviewFixture {")
    esc = chr(92) + chr(92)
    print(f'    const val routePolyline = "{route_poly.replace(chr(92), esc)}"')
    print(f'    const val elevationPolyline = "{elev_poly.replace(chr(92), esc)}"')
    print("    val bounds = LatLngBounds(")
    print(f"        minLat = {min_lat}, maxLat = {max_lat},")
    print(f"        minLng = {min_lng}, maxLng = {max_lng},")
    print("    )")
    print(f"    val climbRanges = listOf<Pair<Double, Double>>(0.0 to {total})")
    print("}")


if __name__ == "__main__":
    main()
