package com.jpweytjens.barberfish

import com.jpweytjens.barberfish.datatype.shared.WindSockGeometry
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The drawables are generated by scripts/gen_wind_sock_drawables.py; WindSockGeometry is what the
 * renderer and the map placement believe about them. This test is the seam between the two.
 */
class WindSockDrawablesTest {

    private fun drawable(bands: Int): String {
        val root =
            generateSequence(File("").absoluteFile) { it.parentFile }
                .first { File(it, "settings.gradle.kts").exists() }
        return File(root, "app/src/main/res/drawable/ic_wind_sock_$bands.xml").readText()
    }

    @Test
    fun every_drawable_is_the_icon_square() {
        for (bands in 1..WindSockGeometry.MAX_BANDS) {
            val xml = drawable(bands)
            assertTrue(xml.contains("android:width=\"64dp\""))
            assertTrue(xml.contains("android:height=\"64dp\""))
            assertTrue(xml.contains("android:viewportWidth=\"64\""))
        }
    }

    @Test
    fun outline_runs_from_the_mouth_at_centre_to_the_tip_one_length_up() {
        for (bands in 1..WindSockGeometry.MAX_BANDS) {
            val xml = drawable(bands)
            val outline =
                Regex("<!-- outline -->\\s*<path[^>]*android:pathData=\"([^\"]+)\"")
                    .find(xml)
                    ?.groupValues
                    ?.get(1) ?: error("no outline path in sock $bands")
            val ys =
                Regex("[ML](-?[0-9.]+),(-?[0-9.]+)")
                    .findAll(outline)
                    .map { it.groupValues[2].toFloat() }
                    .toList()
            val centre = WindSockGeometry.ICON_SIZE_DP / 2f
            assertEquals(centre, ys.max(), 0.01f)
            assertEquals(centre - WindSockGeometry.lengthDp(bands), ys.min(), 0.01f)
        }
    }

    @Test
    fun band_count_matches_the_filled_polygons() {
        for (bands in 1..WindSockGeometry.MAX_BANDS) {
            val xml = drawable(bands)
            val fills = Regex("android:fillColor=\"#(FF6A00|FFFFFF)\"").findAll(xml).count()
            assertEquals(bands, fills)
            assertTrue(
                xml.indexOf("#FF6A00") <
                    xml.indexOf("#FFFFFF").let { if (it < 0) Int.MAX_VALUE else it }
            )
        }
    }

    @Test
    fun length_is_band_count_times_band_length() {
        assertEquals(6.4f, WindSockGeometry.lengthDp(1), 0.001f)
        assertEquals(32f, WindSockGeometry.lengthDp(5), 0.001f)
    }
}
