package com.jpweytjens.barberfish.datatype.shared

import androidx.annotation.DrawableRes
import com.jpweytjens.barberfish.R

// Generated by scripts/generate_chevron_drawables.py. Do not edit by hand.
// Maps grade-band ARGB ints to the matching pre-baked chevron drawable.

@DrawableRes
internal fun gradeChevronDrawable(colorArgb: Int): Int = when (colorArgb) {
    0xFF04fe00.toInt() -> R.drawable.ic_climber_chevron_04fe00
    0xFF2bc7f0.toInt() -> R.drawable.ic_climber_chevron_2bc7f0
    0xFF30f0a9.toInt() -> R.drawable.ic_climber_chevron_30f0a9
    0xFF39a7d6.toInt() -> R.drawable.ic_climber_chevron_39a7d6
    0xFF401c4c.toInt() -> R.drawable.ic_climber_chevron_401c4c
    0xFF540000.toInt() -> R.drawable.ic_climber_chevron_540000
    0xFF5783e9.toInt() -> R.drawable.ic_climber_chevron_5783e9
    0xFF6ebe43.toInt() -> R.drawable.ic_climber_chevron_6ebe43
    0xFF8e1201.toInt() -> R.drawable.ic_climber_chevron_8e1201
    0xFFaa0200.toInt() -> R.drawable.ic_climber_chevron_aa0200
    0xFFb0f94d.toInt() -> R.drawable.ic_climber_chevron_b0f94d
    0xFFbc2900.toInt() -> R.drawable.ic_climber_chevron_bc2900
    0xFFdd4700.toInt() -> R.drawable.ic_climber_chevron_dd4700
    0xFFea5147.toInt() -> R.drawable.ic_climber_chevron_ea5147
    0xFFeb6d66.toInt() -> R.drawable.ic_climber_chevron_eb6d66
    0xFFed1b24.toInt() -> R.drawable.ic_climber_chevron_ed1b24
    0xFFf1d749.toInt() -> R.drawable.ic_climber_chevron_f1d749
    0xFFf2c510.toInt() -> R.drawable.ic_climber_chevron_f2c510
    0xFFf36c72.toInt() -> R.drawable.ic_climber_chevron_f36c72
    0xFFf9ee44.toInt() -> R.drawable.ic_climber_chevron_f9ee44
    0xFFfa5e60.toInt() -> R.drawable.ic_climber_chevron_fa5e60
    0xFFfbad41.toInt() -> R.drawable.ic_climber_chevron_fbad41
    0xFFfe8253.toInt() -> R.drawable.ic_climber_chevron_fe8253
    0xFFfe932c.toInt() -> R.drawable.ic_climber_chevron_fe932c
    0xFFfeff00.toInt() -> R.drawable.ic_climber_chevron_feff00
    0xFFff5501.toInt() -> R.drawable.ic_climber_chevron_ff5501
    0xFFff5958.toInt() -> R.drawable.ic_climber_chevron_ff5958
    0xFFff5959.toInt() -> R.drawable.ic_climber_chevron_ff5959
    0xFFff5c23.toInt() -> R.drawable.ic_climber_chevron_ff5c23
    else -> R.drawable.ic_climber_chevron
}
