// Generated by scripts/gpx_to_climb_fixture.py - do not edit by hand.
package com.jpweytjens.barberfish.datatype.shared

/** Route fixture for the climb overlay config preview. Km 166-172 of "Reina":
 *  the Collao Laguar por Castells climb. */
internal object ClimbPreviewFixture {
    const val routePolyline = "{tokFri^~@yA`AwARa@Ro@PoA?sBEmAa@u@Ow@Ea@UIIHP`AFbAAHGJS?CEW}AQ[i@a@g@Oy@?a@ZU?mBQkCOy@TSIGGK_@SgA?qAGUYm@K_@UcBBcA_A}BKK[UOEMDED?z@HrAWbBGHUJ[OaCuCKUAw@Oq@@KHO^UV[ZsAHu@BcAR{@B[AgAGo@Ym@QWg@I]OQUm@uB][w@_@MQQIKEUDUTWHOCSq@s@k@CECw@c@}AGKG?EDAJAp@FX?PS`AGDEEWaAg@e@GAgATEDAZRpA?r@FTd@`Af@v@`@z@Z|@Pz@p@zB`@xCA|@Id@MP]X[l@ET?^JlAB|AErAi@`B_@jBGNe@v@ATHfA@x@Ab@IlADvBEFG?SO[a@Oi@IqBe@_CIk@?e@Dm@AOg@oA]_AQwCOyCSmA{@aB]a@e@OI?SBo@Ts@`@KDGECEE[VqEEgAIa@GIMEIDEHChBOfAe@rBKlACp@@ZJd@JVVNHNZhB@TAJUHsBTq@JQ?KEo@_CIi@Bg@TyA?_@Ia@i@sAGIE?IBCPPv@?RWl@W`@m@t@Uf@Ed@Hp@AZOTSNSDOEq@_@Ug@c@}A[QaCYYO_@a@{AyB_@Uy@gAGUC[Nq@LUJKbAe@LK`@w@D[@gAK}A_@iCGEE@ERFtCArAUj@MF_AF{B|@e@?QTEd@"
    const val elevationPolyline = "?{uFa`@h@_`@d@qJFwMJqUBm^?gTEyQ\\cONmHDcGHmCT}QVsQByA?gCC_FAcA?yYLyHAgPKqMKeSM_MCsF?qe@Qyo@qAaTc@mFEoB?sHEwSGeUg@sE?kNg@sH{@c[e@oQm@wg@uCiDc@kJ?yDgAcD?sAIgOg@aVgAi[}A}B?gG_AuIm@w{@qDiFMeNQsMOiBAqDAsK?gJMwWqAaNYoQo@uPoAuFUoRk@iL_@kNe@aHWcMYiJIsGWwb@}@}Kk@gTcA}Ea@yE?mCc@yFUuHe@yGUsDMgNUsT[eAKeN]k[iBiC]wA?uA?iB}@qL[qFu@{C?eRiCgB?sA?wRaAgPgA{A?uXwBuAo@qFOiVwAaMQsE?eUCsS_@aSa@mRQkPA{d@?kj@IyOGyIC}E?qKByNEiEGuGSoTq@qXw@yUYi]e@i^uBcD]cSi@_ECyRUwNYwHYmTo@q_@_CaBAwA?eGs@mLWsKs@c^cAad@q@mKSiIOsKQkCCwXy@gSU{h@}B{h@oCgUqBw`@gC}L_@{LOoB?_FCwPKgSe@oC?eBKcAC{FEox@qBsRo@{Hq@{B?cDg@{B?kBWw[m@iSMaa@}AqT_@sLq@sFc@cJOuF?kHo@qD?k]wA_E{@iB?cG?wg@wCsPo@gEs@oCKoe@oA{JU}IWqXsAuGUyHo@aZmB{B?aAUsBIcDGkOOmDY_N?mKMsTg@gL?qIQ}LSsFQeGMeGWcFQyDe@kRi@gLu@k[k@}Iw@ul@o@_ICmM@_m@BsK?a[EqE?uFMuMEuFEgDQyXQyDCgRC{FVoRZyX`@_f@gAgB?cA]yDSwg@_CwUaAeMg@iD_@kUi@gm@}@eLo@sGUoIu@"
    val bounds = LatLngBounds(
        minLat = 38.74969627031598, maxLat = 38.76880347030962,
        minLng = -0.16670160706335674, maxLng = -0.14219839293664327,
    )
    val climbRanges = listOf<Pair<Double, Double>>(500.0 to 5956.0)
}
