// Generated by scripts/gpx_to_climb_fixture.py - do not edit by hand.
package com.jpweytjens.barberfish.datatype.shared

/**
 * Route fixture for the climb overlay config preview. Km 167.5-169.25 of "Reina": the Collao Laguar
 * por Castells climb.
 */
internal object ClimbPreviewFixture {
    const val routePolyline =
        "kqpkFf~\\V[ZsAHu@BcAR{@B[AgAGo@Ym@QWg@I]OQUm@uB][w@_@MQQIKEUDUTWHOCSq@s@k@CECw@c@}AGKG?EDAJAp@FX?PS`AGDEEWaAg@e@GAgATEDAZRpA?r@FTd@`Af@v@`@z@Z|@Pz@p@zB`@xCA|@Id@MP]X[l@ET?^JlAB|AErAi@`B_@jBGNe@v@ATHfA@x@Ab@IlA"
    const val elevationPolyline =
        "?wuGgJMwWqAaNYoQo@uPoAuFUoRk@iL_@mNe@_HWeMYgJIsGWwb@}@}Kk@iTcA{Ea@yE?mCc@yFUwHe@wGUsDMgNUsT[eAKgN]k[iBgC]wA?uA?iB}@qL[qFu@{C?eRiCgB?sA?wRaAiPgAyA?uXwBuAo@sFOgVwAaMQsE?eUCsS_@aSa@mRQmPAyd@?kj@IyOG{IC{E?qKByNEiEGuGSqTq@oXw@yUYi]e@i^uBeD]aSi@_ECyRUwNYyHYkTo@"
    val bounds =
        LatLngBounds(
            minLat = 38.75340452136414,
            maxLat = 38.76174528059615,
            minLng = -0.158603,
            maxLng = -0.147907,
        )
    val climbRanges = listOf<Pair<Double, Double>>(0.0 to 1698.0307226798018)
}
