// Generated by scripts/synth_climb_fixture.py - do not edit by hand.
package com.jpweytjens.barberfish.datatype.shared

/**
 * Synthetic route fixture for the climb overlay config preview: a winding climb whose grade walks
 * the full palette. Not a real place.
 */
internal object ClimbPreviewFixture {
    const val routePolyline =
        "}f{rG_nwf@EREXEZG^G`@Id@Id@Ih@Ih@Ij@Kj@Il@Kl@Kl@Il@Kl@Kj@Ij@Kh@Ih@If@Ib@Gd@Id@If@If@Ih@Gj@Ih@Ih@Ih@Gf@If@Id@Gb@I`@G^I\\GXGTGPGLGHEDG?EGGOESEWC]E_@Ec@Ce@Eg@Ci@Eg@Cg@Ce@Ee@Ca@C]E[CUEOCIECE@CFEHCNERETCXEXE\\C^E`@E`@Cb@Eb@E`@Cb@E`@E`@C^E\\EZCXEXEXCZEZEZC\\E\\EZC\\EZCZEXEVCVETERCNELEJCHEBE@CAECEICKEMEOCSEUEWCWEYE[C[E]C[E]E]C[E[E[CYEYEYC[E]E_@Ca@Ea@Ec@Ca@Ec@Ec@Ca@Ea@E_@C]EYEYCUESCOEIEGCAE@EFCHENERCTEXEXC\\E^E`@C`@Eb@Eb@C`@Eb@E`@C`@E^E\\CZEXCXEXEZCZEZE\\C\\EZE\\CZEZEXCVEVETCRENELCJEHEBC@EAECCIEKCMEOESCUEWEWCYE[E[C]E[E]C]E[E[C[EYEYCYE[E]C_@Ea@Ea@Cc@Ea@Ec@Cc@Ea@Ca@E_@E]CYEYEUCSEOEICGEAE@CFEHENCRETEXCXE\\E^C`@E`@Eb@Cb@E`@Cb@E`@E`@C^E\\EZCXEXEXCZEZEZC\\E\\EZC\\EZEZCXEVEVCTERENCLEJCHEBE@CAECEICKEMEOCSEUEWCWEYE[C[E]E[C]E]E[C[E[EYCYEYC[E]E_@Ca@Ea@Ec@Ca@Ec@Ec@Ca@Ea@E_@C]EYEYCUESEOCIEGEAC@EHCLCPEVCZC\\C^E`@Cb@Cd@Cd@Ed@Cb@Eb@E`@E^EZEXETGPGJGFGBI@I?ICIEIGIIKIIKKMIKKMKKKMIKKIKIIGKEICK?I?K@KBKBKDKDKFKFKHKFKHKHKHKFIHIHIFGFIDEDGDEB"
    const val elevationPolyline =
        "??sDCqECkFCeGE}GEoHEcIGsIG_JGkJGsJGyJI}JI_KI}JG{JIuJImJIaJIwIIgIGuHIsHG_IIkIIsIIyIK{II}IK{IKwIKqIKgIK{HKmHK_HKiGIwFI_FIeEGiDGoCEsBE{ACmAA_BCeCEkDGoEImFKiGK_HMqHM{HOaIOcIQ}HOuHOeHOoGOwFMyEKuDIkCGcBEaAC}@CqACkBEeCGaDIwDKoEKaFMqFM_GOkGQsGQyGQ{GQ}GSyGQuGQmGSaGQsFOeFOqEOmEMuEO_FOeFQkFQkFQoFQkFQkFQcFQ_FQwEOkEOaEOqDMcDMsCK_CImBIyAGgAE}@C{@EgAE{AEkBIaCIqCMcDMsDM_EQmEQuEQ_FSeFSiFUmFSmFUmFUiFUeFS_FUwESmESqEScFUuFWaGWkGYuG[yG[}G[{G]yG]sG]kG]_G[sF[aFYmEWyDU_DSgCOkBMqAI}@G}@GqAIiBMgCOaDUwDWoEYaF]qFa@_Ga@kGe@sGe@yGg@{Gi@}Gi@yGk@uGi@mGi@aGg@sFg@eFc@qEa@kEa@wEc@_Fe@eFe@kFg@kFi@oFi@kFi@iFi@eFi@_Fe@wEe@kEc@_Ea@sD_@cD[qCWaCUmBQyAOgAK}@I{@IgAK{AOkBQaCUqCWcDYsD]_E]mE_@uEc@_Fa@eFc@iFc@mFc@mFc@mFc@iFc@eFa@_F_@wE_@mE[qE]cF_@sFa@cGc@kGe@uGc@yGe@}Ge@{Gc@yGc@sGc@kG_@_G_@sF]aF[mEWyDU_DSgCOkBKoAI_AG}@EoAIkBKgCO_DQyDUmEUaFYsFY_G[kG[sG]yG[{G]}G]yG[uGYkGYcGYsFUeFUqESkEQwES_FSeFSkFSkFSmFSmFSiFSeFQ_FQwEQkEO_EMsDMcDKqCKaCImBGyAGgAC}@E{@CgAEyAEmBGaCIqCIcDKsDM_EMmEMuEO_FOeFOiFOmFQmFOmFOiFOeFM_FOwEMkEMqEKeFOsFMcGQkGOuGOyGQ}GQ{GOyGOsGOkGO_GMsFMaFKmEKyDI_DGgCEkBEoAC_AC}@CyACyBE}CG}DIwEKoFKeGKsGM_HMiHMkHMiHMgHK}GMqGKaGKmFIuEI{DG}CEcCEmBCgBCcBCiBCqBEyBCaCEkCEsCE{CE}CEaDEeDEaDEaDE_DEwCEsCEkCEcCC}BCwBCwBE_CCcCCgCEoCCqCCuCEwCEyCCyCEwCCwCEsCCqCCkCEcCC}BCuBAkBC_BCuAAgAA"
    val bounds =
        LatLngBounds(
            minLat = 45.199874148015354,
            maxLat = 45.21395966723932,
            minLng = 6.499884047081395,
            maxLng = 6.519876309448953,
        )
    val climbRanges = listOf<Pair<Double, Double>>(0.0 to 4118.780750858535)
}
